### ISSUE TITLE
Update to python-oracledb

### ISSUE THREAD

**Issue by cjbj** [aws-samples/aws-lambda-python-oracle-connection#1]
[python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) is the upgrade from cx_Oracle - and it doesn't necessarily need Oracle Instant Client.  This should make installation easier.

**Comment by nicolasbaer** [comment]
Thanks @cjbj, let me try it out in a lambda and update the doc here accordingly.

**Comment by cjbj** [comment]
@nicolasbaer any update?

**Comment by nicolasbaer** [comment]
@cjbj opened a pull request and would appreciate a second pair of eyes - see above.

**Comment by cjbj** [comment]
I did a quick pass through.  Nothing major sprang out.  But note I was not reviewing the technical side.
